### ISSUE TITLE
Wrong Omada-Ports

### ISSUE THREAD

**Issue by hannpet** [lougovsk/ha-omada-controller-addon#1]
I installed your Addon and then had problems adopting my Access-points into the controller (nothing was found).
Somewhere on the TP-Link website, I found that those Ports are needed for provisioning:

UDP 29810 
TCP 29811 
TCP 29812 
TCP 29813
TCP 29814

After I changed it, everything works. So maybe that's useful for a bugfix.
Thanks for your efforts!

**Comment by lougovsk** [comment]
Sorry copy-paste bug
